# github actions: 로직을 실행시킬 수 있는 컴퓨터
# Workflow: 일련의 과정
# name = workflow의 이름
name: Github Actions 실행시켜보기

# Event: 실생되는 시점을 설정

# on: 어떤 시점에 실행시킬것인지?
on:
  # main이라는 브랜치에 push가 될 때 아래 Workflow를 실행
  push:
    branches:
      - main

# 하나의 workflow는 1개 이상의 Job으로 구성된다.
# 여러 Job은 기본적으로 병렬수행이 된다.
jobs:
  # Job을 식별하기 위한 id
  My-Deploy-Job:
    # 운영체제 고르기: ubuntu 환경 / 가장 최신 버전(latest)
    runs-on: ubuntu-latest

    # step: 특정 작업을 수행하는 가장 작은 단위
    # 하나의 job은 여러 step들로 구성되어 있다.
    steps:
      # 스텝의 이름
      - name: Hello World 찍기
        # 실제 코드 작성(linux 코드)
        # helloWorld를 출력해줘라
        run: echo "Hello World"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"